In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("D:\\csss\\m32017.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12690 entries, 0 to 12689
Columns: 111 entries, loan_amnt to unique_id
dtypes: float64(86), int64(6), object(19)
memory usage: 10.7+ MB

In [83]:
print(df.isna())

       loan_amnt  funded_amnt  funded_amnt_inv   term  int_rate  installment  \
11         False        False            False  False     False        False
12         False        False            False  False     False        False
14         False        False            False  False     False        False
15         False        False            False  False     False        False
21         False        False            False  False     False        False
...          ...          ...              ...    ...       ...          ...
12669      False        False            False  False     False        False
12670      False        False            False  False     False        False
12674      False        False            False  False     False        False
12676      False        False            False  False     False        False
12680      False        False            False  False     False        False

       grade  sub_grade  emp_title  emp_length  ...  sec_app_revol_util  \
11     False      False      False       False  ...               False
12     False      False      False       False  ...               False
14     False      False      False       False  ...               False
15     False      False      False       False  ...               False
21     False      False      False       False  ...               False
...      ...        ...        ...         ...  ...                 ...
12669  False      False      False       False  ...               False
12670  False      False      False       False  ...               False
12674  False      False      False       False  ...               False
12676  False      False      False       False  ...               False
12680  False      False      False       False  ...               False

       sec_app_open_act_il  sec_app_num_rev_accts  \
11                   False                  False
12                   False                  False
14                   False                  False
15                   False                  False
21                   False                  False
...                    ...                    ...
12669                False                  False
12670                False                  False
12674                False                  False
12676                False                  False
12680                False                  False

       sec_app_chargeoff_within_12_mths  sec_app_collections_12_mths_ex_med  \
11                                False                               False
12                                False                               False
14                                False                               False
15                                False                               False
21                                False                               False
...                                 ...                                 ...
12669                             False                               False
12670                             False                               False
12674                             False                               False
12676                             False                               False
12680                             False                               False

       issue_d_new  loan_default  issue_year  issue_month  unique_id
11           False         False       False        False      False
12           False         False       False        False      False
14           False         False       False        False      False
15           False         False       False        False      False
21           False         False       False        False      False
...            ...           ...         ...          ...        ...
12669        False         False       False        False      False
12670        False         False       False        False      False
12674        False         False       False        False      False
12676        False         False       False        False      False
12680        False         False       False        False      False

[2925 rows x 106 columns]

In [19]:
df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,term,installment,emp_length,annual_inc,dti,delinq_2yrs,fico_range_low,...,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,loan_default,issue_year,issue_month,unique_id
count,12690.000000,12690.000000,12690.000000,12690.000000,12690.000000,12690.000000,1.269000e+04,12682.000000,12690.000000,12690.000000,...,353.000000,351.000000,353.000000,353.000000,353.000000,353.000000,12690.000000,12690.0,12690.0,1.269000e+04
mean,14664.066194,14664.066194,14659.513396,41.891253,444.423809,5.618834,8.179952e+04,18.779238,0.344996,696.856974,...,11.515581,60.306268,3.002833,13.181303,0.014164,0.053824,0.161072,2017.0,3.0,1.501661e+07
std,9334.292433,9334.292433,9331.597513,10.329163,281.513616,3.904702,9.764912e+04,15.938735,0.914055,32.231560,...,6.385389,25.062716,3.457123,8.090468,0.118336,0.260993,0.367612,0.0,0.0,2.889895e+06
min,1000.000000,1000.000000,1000.000000,36.000000,30.120000,0.000000,0.000000e+00,0.000000,0.000000,660.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.0,3.0,1.000026e+07
25%,7500.000000,7500.000000,7500.000000,36.000000,239.210000,2.000000,4.805600e+04,12.200000,0.000000,670.000000,...,7.000000,42.400000,1.000000,7.000000,0.000000,0.000000,0.000000,2017.0,3.0,1.250211e+07
50%,12000.000000,12000.000000,12000.000000,36.000000,369.020000,5.000000,6.800000e+04,17.910000,0.000000,690.000000,...,11.000000,63.200000,2.000000,12.000000,0.000000,0.000000,0.000000,2017.0,3.0,1.501054e+07
75%,20000.000000,20000.000000,20000.000000,36.000000,593.490000,10.000000,9.800000e+04,24.360000,0.000000,715.000000,...,15.000000,80.350000,4.000000,18.000000,0.000000,0.000000,0.000000,2017.0,3.0,1.749261e+07
max,40000.000000,40000.000000,40000.000000,60.000000,1568.250000,10.000000,8.500000e+06,999.000000,16.000000,845.000000,...,46.000000,101.500000,28.000000,51.000000,1.000000,2.000000,1.000000,2017.0,3.0,1.999940e+07

In [73]:
df.isna().sum().head(60)

loan_amnt                      0
funded_amnt                    0
funded_amnt_inv                0
term                           0
int_rate                       0
installment                    0
grade                          0
sub_grade                      0
emp_title                      0
emp_length                     0
home_ownership                 0
annual_inc                     0
verification_status            0
issue_d                        0
pymnt_plan                     0
purpose                        0
title                          0
zip_code                       0
addr_state                     0
dti                            0
delinq_2yrs                    0
earliest_cr_line               0
fico_range_low                 0
fico_range_high                0
inq_last_6mths                 0
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                     0
total_acc                      0
initial_list_status            0
collections_12_mths_ex_med     0
mths_since_last_major_derog    0
policy_code                    0
application_type               0
acc_now_delinq                 0
tot_coll_amt                   0
tot_cur_bal                    0
open_acc_6m                    0
open_act_il                    0
open_il_12m                    0
open_il_24m                    0
mths_since_rcnt_il             0
total_bal_il                   0
il_util                        0
open_rv_12m                    0
open_rv_24m                    0
max_bal_bc                     0
all_util                       0
total_rev_hi_lim               0
inq_fi                         0
total_cu_tl                    0
inq_last_12m                   0
acc_open_past_24mths           0
avg_cur_bal                    0
bc_open_to_buy                 0
bc_util                        0
chargeoff_within_12_mths       0
mo_sin_old_il_acct             0
mo_sin_old_rev_tl_op           0
dtype: int64

In [95]:
print(df.columns.tolist())

['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'pymnt_plan', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'policy_code', 'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'issue_d_new', 'loan_default', 'issue_year', 'issue_month', 'unique_id']

import pandas as pd

# 1. Drop rows with null values in specific columns
df.dropna(subset=['emp_title', 'mths_since_rcnt_il', 'mths_since_last_major_derog', 'il_util', 'bc_open_to_buy', 'bc_util'], inplace=True)

# 2. Drop the unnecessary columns
df.drop(columns=[
    'mths_since_last_delinq', 
    'mths_since_last_record', 
    'annual_inc_joint', 
    'dti_joint', 
    'verification_status_joint'
], inplace=True)

# Save the updated dataset back to the file (overwrite the original dataset)
df.to_csv('D:\\csss\\m32017.csv', index=False)  # This will overwrite the original file

import pandas as pd

# Use raw string to avoid issues with backslashes
file_path = r'D:\csss\m32017.xlsx'

# Load the Excel file
try:
    df = pd.read_excel(file_path)
    print("File loaded successfully!")
except FileNotFoundError:
    print(f"File not found at {file_path}. Please check the file path.")
file_path = r'D:\csss\m32017.csv'

# Load the CSV file
try:
    df = pd.read_csv(file_path)
    print("CSV file loaded successfully!")
except FileNotFoundError:
    print(f"CSV file not found at {file_path}. Please check the file path.")

In [164]:
import pandas as pd

# Load the real CSV dataset
df = pd.read_csv('D:\\csss\\m32017.csv')  # Replace with the actual file path of your CSV file

# 1. Fill 'sec_app_revol_util' with mean
df['sec_app_revol_util'] = df['sec_app_revol_util'].fillna(df['sec_app_revol_util'].mean())

# 2. Fill 'sec_app_open_act_il' with median
df['sec_app_open_act_il'] = df['sec_app_open_act_il'].fillna(df['sec_app_open_act_il'].median())

# 3. Fill 'sec_app_num_rev_accts' with median
df['sec_app_num_rev_accts'] = df['sec_app_num_rev_accts'].fillna(df['sec_app_num_rev_accts'].median())

# 4. Fill 'sec_app_chargeoff_within_12_mths' with mode (most frequent value)
df['sec_app_chargeoff_within_12_mths'] = df['sec_app_chargeoff_within_12_mths'].fillna(df['sec_app_chargeoff_within_12_mths'].mode()[0])

# 5. Fill 'sec_app_collections_12_mths_ex_med' with mode (most frequent value)
df['sec_app_collections_12_mths_ex_med'] = df['sec_app_collections_12_mths_ex_med'].fillna(df['sec_app_collections_12_mths_ex_med'].mode()[0])

# 6. Fill 'il_util' with mean
df['il_util'] = df['il_util'].fillna(df['il_util'].mean())

# 7. Fill 'bc_open_to_buy' with mean
df['bc_open_to_buy'] = df['bc_open_to_buy'].fillna(df['bc_open_to_buy'].mean())

# 8. Fill 'bc_util' with median (or mean if preferred)
df['bc_util'] = df['bc_util'].fillna(df['bc_util'].median())

# Check existing columns
print("Columns in the DataFrame:")
print(df.columns.tolist())

# 9. Drop rows with null values in the specified additional columns
subset_columns = [
    'revol_bal_joint', 
    'sec_app_fico_range_low', 
    'sec_app_fico_range_high', 
    'sec_app_earliest_cr_line', 
    'sec_app_inq_last_6mths', 
    'sec_app_mort_acc', 
    'sec_app_open_acc'
]

# Ensure all specified columns exist in the DataFrame
existing_columns = [col for col in subset_columns if col in df.columns]
if existing_columns:
    df.dropna(subset=existing_columns, inplace=True)

# Fill any remaining NaN values with 0
df.fillna(0, inplace=True)

# Save the updated dataset with a different name or in another folder
df.to_csv('D:\\csss\\m32017_modified_v2.csv', index=False)  # This will save it with a new name

print("File updated, null values handled, and saved successfully.")

Columns in the DataFrame:
['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'pymnt_plan', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'policy_code', 'application_type', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'dr', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'issue_d_new', 'loan_default', 'issue_year', 'issue_month', 'unique_id']
File updated, null values handled, and saved successfully.

In [168]:
df.dropna()
df.isna().sum().head(60)

loan_amnt                      0
funded_amnt                    0
funded_amnt_inv                0
term                           0
int_rate                       0
installment                    0
grade                          0
sub_grade                      0
emp_title                      0
emp_length                     0
home_ownership                 0
annual_inc                     0
verification_status            0
issue_d                        0
pymnt_plan                     0
purpose                        0
title                          0
zip_code                       0
addr_state                     0
dti                            0
delinq_2yrs                    0
earliest_cr_line               0
fico_range_low                 0
fico_range_high                0
inq_last_6mths                 0
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                     0
total_acc                      0
initial_list_status            0
collections_12_mths_ex_med     0
mths_since_last_major_derog    0
policy_code                    0
application_type               0
acc_now_delinq                 0
tot_coll_amt                   0
tot_cur_bal                    0
open_acc_6m                    0
open_act_il                    0
open_il_12m                    0
open_il_24m                    0
mths_since_rcnt_il             0
total_bal_il                   0
il_util                        0
open_rv_12m                    0
open_rv_24m                    0
max_bal_bc                     0
all_util                       0
total_rev_hi_lim               0
inq_fi                         0
total_cu_tl                    0
inq_last_12m                   0
acc_open_past_24mths           0
avg_cur_bal                    0
bc_open_to_buy                 0
bc_util                        0
chargeoff_within_12_mths       0
mo_sin_old_il_acct             0
mo_sin_old_rev_tl_op           0
dtype: int64